apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "president.fullname" . }}-redis-pvc
  labels:
    app: {{ include "president.name" . }}-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "president.fullname" . }}-redis
  labels:
    app: {{ include "president.name" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "president.name" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "president.name" . }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "president.fullname" . }}-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "president.fullname" . }}-redis
  labels:
    app: {{ include "president.name" . }}-redis
spec:
  ports:
    - port: 6379
  selector:
    app: {{ include "president.name" . }}-redis
