# Default values for president stack

postgres:
  image: postgres:16-alpine
  # Au lieu de mettre les identifiants en clair, on pointe vers notre secret
  existingSecret: "db-secret"
  persistence:
    size: 1Gi

redis:
  image: redis:7-alpine
  persistence:
    size: 1Gi

back:
  image: my-registry/president-back:latest
  replicas: 2
  nodeEnv: production

gameServer:
  image: my-registry/president-game-server:latest
  replicas: 2
  nodeEnv: production
